### ISSUE TITLE
Error when try to convert pixi.js.d.ts to pixijs.swc

### ISSUE THREAD

**Issue by enver2007** [BowlerHatLLC/dts2as#13]
D:\HelloPixi>dts2as --flexHome D:\flexjs --outSWC pixijs.swc pixi.js.d.ts
C:\Users\a\AppData\Roaming\npm\node_modules\dts2as\bin\parser.js:437
        var result = this._currentSourceFile.text.substring(ts["skipTrivia"](this._currentSourceFile.text, name.pos), name.end);
                                                                                                               ^

TypeError: Cannot read property 'pos' of undefined
    at TS2ASParser.declarationNameToString (C:\Users\a\AppData\Roaming\npm\node_modules\dts2as\bin\parser.js:437:112)
    at TS2ASParser.readClass (C:\Users\a\AppData\Roaming\npm\node_modules\dts2as\bin\parser.js:1006:30)
    at TS2ASParser.readPackageLevelDefinitions (C:\Users\a\AppData\Roaming\npm\node_modules\dts2as\bin\parser.js:640:41)
    at C:\Users\a\AppData\Roaming\npm\node_modules\dts2as\bin\parser.js:548:31
    at visitEachNode (C:\Users\a\AppData\Roaming\npm\node_modules\dts2as\node_modules\typescript\lib\typescript.js:7195:30)
    at Object.forEachChild (C:\Users\a\AppData\Roaming\npm\node_modules\dts2as\node_modules\typescript\lib\typescript.js:7352:24)
    at TS2ASParser.readPackageLevelDefinitions (C:\Users\a\AppData\Roaming\npm\node_modules\dts2as\bin\parser.js:539:24)
    at TS2ASParser.readSourceFile (C:\Users\a\AppData\Roaming\npm\node_modules\dts2as\bin\parser.js:225:14)
    at C:\Users\a\AppData\Roaming\npm\node_modules\dts2as\bin\parser.js:124:19
    at Array.forEach (native)

**Comment by joshtynjala** [comment]
I'm sorry that you're having some trouble! Unfortunately, I cannot reproduce this issue. I just downloaded the latest pixi.js.d.ts file, and I could use it with dts2as successfully on Windows. Can you double-check the contents of your pixi.js.d.ts file? Is there any HTML in there, by chance?

**Comment by enver2007** [comment]
You are right it was my mistake i have download pixi.js.d.ts with right click and save as

**Comment by joshtynjala** [comment]
I'm glad we got it figured out. I've updated the text in the tutorial to make it more clear that you need to go to the Github site and get the raw version.
