### ISSUE TITLE
Errors when generating swc

### ISSUE THREAD

**Issue by alamboley** [BowlerHatLLC/dts2as#16]
Hi Josh, first time trying dts2as and I run into several issues. I'm building on OS X.

`dts2as --flexHome /Users/Aymeric/Documents/Workspace/SDKs/flex_js --outSWC pixijs.swc pixi.js.d.ts`

```
usr/local/lib/node_modules/dts2as/bin/cli.js:74
                if (!path.isAbsolute(swcOutputPath)) {
                          ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at Object.<anonymous> (/usr/local/lib/node_modules/dts2as/bin/cli.js:74:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/dts2as/bin/dts2as:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

So I commetend this line but then I got:

```
/usr/local/lib/node_modules/dts2as/bin/cli.js:369
    var result = child_process.spawnSync(compcCommand, compcArgs, {
                               ^
TypeError: Object #<Object> has no method 'spawnSync'
    at compileSWC (/usr/local/lib/node_modules/dts2as/bin/cli.js:369:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/dts2as/bin/cli.js:290:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/dts2as/bin/dts2as:2:1)
    at Module._compile (module.js:456:26)
```

Any ideas?

**Comment by joshtynjala** [comment]
That's weird. It's like it can't find some core modules from Node.js. Which version of Node.js are you using? Which version of dts2as is installed?

```
node -v
dts2as -v
```

**Comment by alamboley** [comment]
So I tried on my PC, same issue.
Node versions: v0.10.22 and v0.10.25
dts2as -v : Version: 0.9.0

**Comment by joshtynjala** [comment]
Maybe it's the old version of Node. Can you try updating to a newer version?

**Comment by alamboley** [comment]
Thanks, it works now!
